name: Maths CI Build

on:
  push:
    paths:
      - 'src/Maths/**/*'
  pull_request:
    paths:
      - 'src/Maths/**/*'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.1.20452.10
    - name: Run Tests and Export NUnit
      run: dotnet test ./src/Maths/Silk.NET.Maths.Tests/Silk.NET.Maths.Tests.fsproj -c Release -f net5.0 -l GitHubActions
  Coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 5.0.100-rc.1.20452.10
    - name: Collect coverage
      run: dotnet test ./src/Maths/Silk.NET.Maths.Tests/Silk.NET.Maths.Tests.fsproj --configuration Release /p:AltCover=true /p:AltCoverCobertura="cobertura.xml"
    - uses: codecov/codecov-action@v1
      with:
        file: ./src/Maths/Silk.NET.Maths.Tests/cobertura.xml