name: Vkd3d
on:
  push:
    branches-ignore:
      - "ci/**"
      - "develop/**"
      - "main"
    paths:
      - build/submodules/vkd3d
      - build/submodules/SPIRV-Tools
      - build/submodules/Vulkan-Headers
      - build/submodules/vkd3d-no-ms-abi.patch
      - build/nuke/Native/Core.cs
      - build/nuke/Native/Vkd3d.cs
      - .github/workflows/vkd3d.yml
      - src/Microsoft/Vkd3dCompiler/*
jobs:
  Build:
    if: github.repository == 'dotnet/Silk.NET'
    strategy:
      fail-fast: false
      matrix:
        env:
          - os: ubuntu-latest
            name: Linux
            nuke_invoke: ./build.sh
            extras: |
              sudo apt-get update 

              wget http://mirrors.kernel.org/ubuntu/pool/main/v/vulkan-loader/libvulkan1_1.3.239.0-1_amd64.deb
              sudo apt install ./libvulkan1_1.3.239.0-1_amd64.deb

              wget http://mirrors.kernel.org/ubuntu/pool/main/v/vulkan-loader/libvulkan-dev_1.3.239.0-1_amd64.deb
              sudo apt install ./libvulkan-dev_1.3.239.0-1_amd64.deb
              
              sudo apt-get install -y xorg-dev spirv-headers wine64-development-tools cmake build-essential

              wget http://mirrors.kernel.org/ubuntu/pool/universe/s/spirv-tools/spirv-tools_2020.1-2_amd64.deb
              sudo apt install ./spirv-tools_2020.1-2_amd64.deb
    name: ${{ matrix.env.name }} Build
    runs-on: ${{ matrix.env.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}
      - name: Checkout submodules, configure git
        run: |
          git submodule update --init --recursive --depth 0 build/submodules/vkd3d
          git submodule update --init --recursive --depth 0 build/submodules/SPIRV-Tools
          git submodule update --init --recursive --depth 0 build/submodules/Vulkan-Headers
          git config --local user.email "9011267+dotnet-bot@users.noreply.github.com"
          git config --local user.name "The Silk.NET Automaton"
      - name: Extra prerequisites
        run: |
          echo running extras
          ${{ matrix.env.extras }}
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Setup .NET 6.0 and .NET 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.201
            7.0.*
      - name: Build vkd3d
        run: ${{ matrix.env.nuke_invoke }} Vkd3d
        env:
          PUSHABLE_GITHUB_TOKEN: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}

